seL4/util_libs

libplatsupport/src/plat/zynq7000/serial.c
The QEMU emulator for Zync-7000 appears to have a bug makes it appear
like the UART timeout interrupt has fired even if the interrupt is
disabled. This causes the libplatsupport driver to make a read even
when no data is available (returning 0x00). This patch changes the
reading guard to check the status register directly rather than
checking interrupts. This works correctly under QEMU and should
continue to work on the actual hardware.
=> Zync-7000 UART: Use status register to check if RX fifo is non-empty

libplatsupport/arch_include/arm/platsupport/spi.h, libplatsupport/plat_include/tk1/platsupport/plat/spi.h, libplatsupport/src/plat/tk1/spi.c
The previous TK1 spi driver had a series of issues which it made it
easier to replace rather than patch.
=> libplatsupport: Rewrite TK1 spi driver

libplatsupport/src/plat/imx6/serial.c, libplatsupport/src/plat/tk1/serial.c, libplatsupport/src/plat/zynq7000/serial.c
serial.h declares serial_configure, but some of the serial drivers call this function uart_configure.
https://github.com/seL4/util_libs/blob/master/libplatsupport/include/platsupport/serial.h#L52
=> libplatsupport: Rename uart_configure to serial_configure to match serial.h declaration

libplatsupport/src/arch/arm/clock.c, libutils/include/utils/attribute.h
~/seL4test/libs/libplatsupport/src/arch/arm/clock.c:45:22: warning: comparison of unsigned enum expression >= 0 is always true [-Wtautological-compare]
((void)((clk->id >= 0 && clk->id < NCLOCKS) || (__assert_fail("clk->id >= 0 && clk->id < NCLOCKS", "~/seL4test/libs/libplatsupport/src/arch/arm/clock.c", 45, __func__),0)));
~~~~~~~ ^  ~
~/seL4test/libs/libplatsupport/src/arch/arm/clock.c:70:12: warning: comparison of unsigned enum expression < 0 is always false [-Wtautological-compare]
if (id < 0 || id >= NCLOCKS) {
~~ ^ ~
~/seL4test/libs/libplatsupport/src/arch/arm/clock.c:105:12: warning: comparison of unsigned enum expression < 0 is always false [-Wtautological-compare]
if (id < 0 || id >= NCLOCKS) {
~~ ^ ~
~/seL4test/libs/libplatsupport/src/arch/arm/clock.c:116:12: warning: comparison …
=> Fixed warnings found by clang

libethdrivers/src/lwip.c, libethdrivers/src/plat/imx6/imx6.c, liblwip/include/lwip/arch/cc.h
RX Ring buffer (rx_cookie) was corrupt and uninitialized causing the system to throw an invalid memory access violation when a new packet was received from the iMX6 ethernet controller.
Fix change the definition of the rx_cookie to be a void * where the actual buffer and meaning is delegated to the file that interface with the stack (in my case I'm using lwip.c).
See commit comments for additional info
=> Fixed memory initialization for preallocated RX ring buffer

libplatsupport/src/mach/zynq/mux.c
The signature of feature_enable() changed to take a 3rd parameter, but this has never been updated here. Adding the parameter prevents a compiler warning.
=> libplatsupport: add missing 3rd parameter to zynq_mux_feature_enable()

libplatsupport/CMakeLists.txt, libplatsupport/arch_include/arm/platsupport/arch/generic_timer.h, libplatsupport/sel4_arch_include/aarch32/platsupport/sel4_arch/util.h, libplatsupport/sel4_arch_include/aarch64/platsupport/sel4_arch/util.h, libplatsupport/src/arch/arm/generic_ltimer.c, libplatsupport/src/arch/arm/generic_timer.c
Update generic timer to work for aarch64 as well as aarch32.
Add a generic timer ltimer implementation which can be included for platforms.
=> Generic timer

libplatsupport/src/arch/arm/generic_ltimer.c
- fix periodic timeouts
- set compare to MAX, rather than 0, when turning off comparisons or we
end up with interrupts all the time.
=> platsupport: fixes for generic_ltimer

libplatsupport/src/fdt.c
The wrong function was called to get the length of the 'size-cells' property of the target device node in the FDT.
=> libplatsupport: Fix wrong function call

libplatsupport/src/plat/hifive/uart.c
The previous implementation made two reads to the rxdata register: One
to check if the Data Empty flag was set and another to grab the actual
data. However, the HiFive UART's rxdata is cleared on read. So this
would return 0xff every time. Now the rxdata is read once, stored in a
variable and operations are done against the value stored in that
variable.
Change-Id: I8f6d746293d0ce39dc5dd42eca485a944f1383a2
=> hifive: Fixed UART Get Character function

libplatsupport/plat_include/rockpro64/platsupport/plat/timer.h, libplatsupport/src/plat/rockpro64/timer.c
When allocating an IRQ from the FDT the IRQ that was allocated should be passed back to the caller in addition to the IRQ handler ID.
For `rockpro64`, the `ltimer` implementation for its second timer should use the IRQ number one greater that the first timer's IRQ number (rather than the first timer's IRQ handler ID).
Fixes sel4/sel4test#25.
=> Return allocated IRQ from FDT

libplatsupport/plat_include/polarfire/platsupport/plat/icicle_mss.h, libplatsupport/plat_include/polarfire/platsupport/plat/serial.h, libplatsupport/src/plat/polarfire/chardev.c, libplatsupport/src/plat/polarfire/uart.c
Signed-off-by: Jesse Millwood <jesse.millwood@dornerworks.com>
=> PolarFire SoC: Initial platform UART support

libplatsupport/include/platsupport/io.h, libplatsupport/src/chardev.h
Cleaning up the code a bit. When const qualifier is used everywhere, there is no need to cast explicitly.
=> clean up code: use const qualifier, remove casts

libplatsupport/tools/helpers.cmake
As it isn't an error for queried files to not exist, a warning message is a bit misleading.
=> platsupport: Remove cmake warning for missing file

.licenseignore, libethdrivers/src/plat/zynq7000/uboot/marvell.c, libethdrivers/src/plat/zynq7000/uboot/net.h, libethdrivers/src/plat/zynq7000/uboot/netdev.h, libethdrivers/src/plat/zynq7000/uboot/phy.c, libethdrivers/src/plat/zynq7000/uboot/phy.h, libethdrivers/src/plat/zynq7000/uboot/system.h, libethdrivers/src/plat/zynq7000/uboot/zynq-common.h, libethdrivers/src/plat/zynq7000/uboot/zynq_zc70x.h
The old license checker that is still running on bamboo needs strictly one space character after the `:`.
That old license checker should be retired when everything is converted, but currently we still need to support both.
=> license: stricter SPDX syntax for bamboo

libutils/include/utils/time.h
This patch avoid some problems with source code that has to work on both 32-bit and 64-bit platforms. Assuming that time is usually an `uint64_t`, the constants defined in `time.h` should be welll aligned with that type. However, there is a quirk here, the code below works fine on 32-bit, but triggers a failure "integer type is 'ull', but format specifier is 'ul'" on 64-bit. 
```
uint64_t timeout = 42000
Debug_LOG_INFO("v = %" PRIu64 " sec", timeout/MS_IN_S);
```
This can be explained as `MS_IN_S` is defined as "1000ull" and `uint64_t` is "ul" (on 64-bit targets). According to C99 section 6.3.1.8  'Usual arithmetic conversions', the resulting expression of an operation will have the type of the highest integer rank of the operands involved, so "ull" wins over "ul".
=> libutils: avoid hard-coding uint64_t assumptions

libplatsupport/plat_include/polarfire/platsupport/plat/serial.h, libplatsupport/plat_include/spike/platsupport/plat/serial.h, libplatsupport/src/plat/spike/serial.c
avoid error due to misaligned comment termiator
```
In file included from .../sel4_util_libs/libplatsupport/include/platsupport/chardev.h:14,
from .../sel4_libs/libsel4platsupport/include/sel4platsupport/platsupport.h:13,
from .../main/camkes.c:14:
.../sel4_util_libs/libplatsupport/plat_include/polarfire/platsupport/plat/serial.h:84:1: error: "/*" within comment [-Werror=comment]
/* Line Control Register */
```
=> trivial: fix comment terminator

libplatsupport/src/mach/zynq/serial.c
Clear the receive trigger interrupt when reading a character, assuming the caller is draining the FIFO anyway. This avoids unnecessary (re-)invocation of the ISR
=> libplatsupport,zynq: clear receive trigger interrupt also when reading chars

libplatsupport/src/plat/imx8m/clock.c
Signed-off-by: Damon Lee <Damon.Lee@data61.csiro.au>
=> trivial: Remove compiler warning for imx8m clock

libcpio/include/cpio/cpio.h, libcpio/src/cpio.c, libelf/include/elf/elf.h, libelf/include/elf/elf32.h, libelf/include/elf/elf64.h, libelf/src/elf.c, libelf/src/elf32.c, libelf/src/elf64.c
CPIO is handling fixed data, so it should use the `const` qualifier wherever possible. This allows passing it const data and use the type checking features from the compiler to find invalid usages. 
Note that this change will break the ElfLoader (at least in strict mode), as it does not use const either. There is a commit in https://github.com/seL4/seL4_tools/pull/54 that fixed this.
=> use const qualifier for libcpio and libelf wherever possible

libplatsupport/mach_include/imx/platsupport/mach/serial.h
Loosely related to https://github.com/seL4/seL4/issues/254 and https://github.com/seL4/seL4/pull/255. Using CONFIG_PLAT_IMX7 feels wrong here and sets a bad example, because this refers to a SOC family and not a specific board. Using CONFIG_PLAT_IMX7_SABRE seems much more sane here. Then it will work for a specific board, but fail for any other IMX7 based platform initially. Whoever ports something has to set the proper configuration here then also.
=> imx7,sabre: use correct platform define

libethdrivers/src/plat/imx6/uboot/imx-regs.h
Fix https://github.com/seL4/util_libs/issues/86, commit taken from https://github.com/seL4/util_libs/pull/83
=> libplatsupport/imx6: add missing include

libplatsupport/src/plat/imx6/clock.c
There was a typo in the derefencing of the clock controllers registers
that fetched the wrong divisor for calculating the frequency of a clock.
Signed-off-by: Damon Lee <Damon.Lee@data61.csiro.au>
=> libplatsupport,imx6: Fix deref typo in arm clock

libutils/include/utils/page.h
This commit adds extra page utility macros for 2 mebibyte pages.
Signed-off-by: Damon Lee <Damon.Lee@data61.csiro.au>
=> libutils: Add 2M page utility macros

libplatsupport/plat_include/odroidc2/platsupport/plat/meson_timer.h, libplatsupport/plat_include/odroidc2/platsupport/plat/odroid_serial.h, libplatsupport/plat_include/odroidc2/platsupport/plat/odroid_timer.h, libplatsupport/plat_include/odroidc2/platsupport/plat/serial.h, libplatsupport/plat_include/odroidc4/platsupport/plat/clock.h, libplatsupport/plat_include/odroidc4/platsupport/plat/i2c.h, libplatsupport/plat_include/odroidc4/platsupport/plat/meson_timer.h, libplatsupport/plat_include/odroidc4/platsupport/plat/odroid_serial.h, libplatsupport/plat_include/odroidc4/platsupport/plat/odroid_timer.h, libplatsupport/plat_include/odroidc4/platsupport/plat/serial.h, libplatsupport/src/plat/odroidc4
This adds support for the ODroidC4. The ODroidC4 is just a beefier ODroidC2 with some bits moved around. The devices we care about here are all essentially the same.
=> Add odroidc4 support

libplatsupport/src/plat/pc99/hpet.c
On clang-11 setting the ENABLE_CNF flag to enable the hpet was getting
compiled to a byte sized `or` operation and not actually enabling the
timer when running on qemu.
=> libplatsupport,hpet: Fix hpet_start clang issue

libplatsupport/plat_include/bcm2711/platsupport/plat/mailbox_util.h, libplatsupport/plat_include/bcm2837/platsupport/plat/mailbox_util.h, libplatsupport/src/plat/bcm2711/mailbox_util.c, libplatsupport/src/plat/bcm2837/mailbox_util.c
Extends the mailbox for the bcm2837 (rpi3) and bcm2711 (rpi4) with additional functionality.
=> Bcm2xxx extend mailbox

libethdrivers/src/plat/imx6/imx6.c
In imx6.c the ZF_LOGI message for promiscuous mode uses wrong variable.
Signed-off-by: Thomas Wittal <thomas.wittal@hensoldt-cyber.de>
=> libethdrivers: imx6 fix log message

libutils/include/utils/config.h
This file was mistakenly tagged as GPL, when it should be BSD. Commit
a7130f9f836 previously already fixed the license text, but not the tag,
which in the SPDX conversion then got lost.
=> util_libs: license clarification

libplatsupport/src/mach/imx/epit/epit.c, libplatsupport/src/mach/imx/gpt.c, libplatsupport/src/mach/imx/ltimer.c
- When programming timeouts using the ltimer, if the timeout is too soon, ETIME needs to be returned instead of attempting to program a timeout which may end up being and underflowed timer value otherwise
- When reading the upcounter, handle the situation when the counter ticks over between reading it and reading the overflow hardware bit.
=> libplatsupport,imx: Update timer drivers to handle more boundary-conditions/edge cases

libethdrivers/plat_include/imx6/ethdrivers/plat/eth_plat.h
The `nic_config_flags_t` enum in the imx6's `eth_plat.h` header is missing the `typedef` keyword, this causes a build error when multiple source files include the header.
=> fix: add missing typedef for imx6 `eth_plat.h`

libpci/src/pci.c
To handle cases where PCI or PCIe buses are not accessible via
a bridge from bus 0, We use "brute force" scan instead of recursive
scan here. Details of these methods can be found on
https://wiki.osdev.org/PCI#.22Brute_Force.22_Scan.
Signed-off-by: Jingyao Zhou <jingyao.zhou@unsw.edu.au>
This is not the ideal solution, but a workaround for this issue: https://github.com/seL4/util_libs/issues/131
=> libpci: use "brute force" scan for devices

libethdrivers/CMakeLists.txt
The symbol name is supposed to be tx2_ether_qos_ptr.
Signed-off-by: Kent McLeod <kent@kry10.com>
=> trivial: Fix typo in linker arg for tx2 ethernet

libplatsupport/CMakeLists.txt, libplatsupport/plat_include/quartz64/platsupport/plat/clock.h, libplatsupport/plat_include/quartz64/platsupport/plat/i2c.h, libplatsupport/plat_include/quartz64/platsupport/plat/serial.h, libplatsupport/src/plat/quartz64/chardev.c, libplatsupport/src/plat/quartz64/serial.c
This adds support for the Pine64 Quartz64 and other devices based on
the Rockchip RK3566. The platform support is adapted from the
Rockpro64 code, except that the RK356x has A55 cores, and adjusting
for the fact that the ARM Generic Timer is the only on-chip timer
available.
Test with: seL4/seL4#727, seL4_tools#134, seL4/sel4test#83
=> Add Quartz64 support

libcpio/src/cpio.c
All paths inside the endless loop (`while (1)`) end in a `return`,
but the function contained another `return 0` at the end of the body,
which was never reached.
Use the EOF path (which returns a 0) inside the loop to jump to that `return 0`.
=> Fix compilation warning about unreachable code

libcpio/src/cpio.c
It is converted to an unsigned type: an "int -1" to "unsigned long".
=> Fix compilation warning about implicit conversion of a negative value

.github/workflows/sel4test-hw.yml
Use the more recent Node.js 16 actions; removes warnings.
=> github: bump GitHub action versions

libutils/include/utils/compile_time.h
`static_assert` and `_Static_assert` were introduced to C11. However gcc and clang support `_Static_assert` for earlier versions. C23 deprecates `_Static_assert`, `static_assert` is changed to a keyword and will be removed from `assert.h`. 
Change compile_time_assert to take these into account.
See also: https://github.com/seL4/seL4_projects_libs/pull/96
=> libutils: compile_time_assert to support various standards

libplatsupport/src/arch/arm/delay.c
Avoid a clang warning.
```
sel4_util_libs/libplatsupport/src/arch/arm/delay.c:60:29: warning: value size does not match register size specified by the constraint and modifier [-Wasm-operand-widths]
"    bpl 1b" : "+r"(cycles));
```
=> libplatsupport: use proper type

libethdrivers/CMakeLists.txt
This line `target_link_libraries(ethdrivers "${DriverModules}")` was removed accidentally in commit 12a8adba (PR https://github.com/seL4/util_libs/pull/136) and this broke support for the various ethernet drivers. I'm a bit surprised that this has not be noticed, but it seem the linker sometimes still keeps modue sections. However, we ran into problems when adding a new driver, as the new module never ended up in the the CAmkES component's binary.
I'm also making the comment a bit more verbose and add a note about better CMake usage once we update the containers (see https://github.com/seL4/seL4/issues/827)
=> libethdrivers: bring back linker options

libutils/include/utils/assume.h
Avoid warning on clang (v11.0.1): "`'cold' attribute only applies to functions`". 
The warning make be think no optimization is happening at all with clang based on this attribute. Anything happening would either be a lucky coincidence oder some other heuristic kicks in. 
This fix allows us to build with clang, as we handle all warnings as errors by default.
=> libplatsupport: avoid clang warning

libplatsupport/mach_include/bcm/platsupport/mach/system_timer.h, libplatsupport/mach_include/exynos/platsupport/mach/pwm.h, libplatsupport/mach_include/omap/platsupport/mach/gpt.h, libplatsupport/plat_include/am335x/platsupport/plat/timer.h, libplatsupport/plat_include/fvp/platsupport/plat/sp804.h, libplatsupport/plat_include/hikey/platsupport/plat/dmt.h, libplatsupport/plat_include/rockpro64/platsupport/plat/timer.h, libplatsupport/plat_include/tqma8xqp1gb/platsupport/plat/gpt.h, libplatsupport/src/ltimer.h, libplatsupport/src/mach/exynos/pwm.c, libplatsupport/src/mach/omap/gpt.c, libplatsupport/src/plat/tqma8xqp1gb/gpt.c
Ensure the const correctness is kept, this avoids compiler warnings.
=> libplatsupport: use const qualifier

.stylefilter, libfdt/libfdt.h
Adds a convenience function that reduces the number of 'if' statements in the code, since #cells required is given as a parameter.
=> libfdt: Add 32/64-bit fdt_appendprop_uint()

libplatsupport/src/plat/hifive/pwm.c
Timer may have been reset, or the overflow may be already handled by pwm_get_time().
This fixes sel4test [issue 91](https://github.com/seL4/sel4test/issues/91).
=> hifive: Check if overflow IRQ is actually pending

libpicotcp/CMakeLists.txt
In GNU `sed`, the suffix is optional for the `-i` argument, but is mandatory for the BSD `sed` shipped with MacOS. This change checks whether the host is an Apple system and if so, supplies a suffix.
=> Change to support BSD sed

.github/workflows/sel4test-hw.yml, .github/workflows/sel4test-sim.yml
Similar to https://github.com/seL4/seL4/pull/1154, pick up things from https://github.com/seL4/ci-actions/pull/297
=> do simulation and HW build with LLVM on RISCV

libplatsupport/src/plat/hifive/ltimer.c
This avoid a build warning with clang, which can also be found in CI (see e.g. https://github.com/seL4/seL4/actions/runs/8085439570/job/22092970792)
```
[78/256] Building C object apps/sel4test-driver/util_libs/libplatsupport/CMakeFiles/platsupport.dir/src/plat/hifive/ltimer.c.obj
/github/workspace/projects/util_libs/libplatsupport/src/plat/hifive/ltimer.c:104:55: warning: format specifies type 'int' but the argument has type 'long' [-Wformat]
ZF_LOGE("Invalid IRQ number: %d received.\n", irq_number);
~~               ^~~~~~~~~~
%ld
/github/workspace/projects/util_libs/libutils/include/utils/zf_log.h:359:43: note: expanded from macro 'ZF_LOGE'
_ZF_LOG_IMP(ZF_LOG_ERROR, _ZF_LOG_TAG, __VA_ARGS__)
^~~~~~~~~~~
/github/workspace/projects/util_libs/libutils/include/utils/zf_log.h:302:18: note: …
```
=> libplatsupport: use proper format specifier

libethdrivers/CMakeLists.txt, libethdrivers/src/plat/zynqmp/zynqmp.c
- fix compatibility string. Seems this changed in at some point in the device tree? Or did this ever work, because that seems the zynq7000 string? 
- add zynqmp driver to the list of symbols kept, so the linker will not throw this out.
@chrisguikema I'm a bit confused actually, how do things work for you without these changes?
=> libethdrivers: make zynqmp driver usable

libplatsupport/include/platsupport/irq.h
Fix the semantics, technically it remains an integer.
=> libplatsupport: use proper return type

libplatsupport/CMakeLists.txt, libplatsupport/plat_include/imx93/platsupport/plat/clock.h, libplatsupport/plat_include/imx93/platsupport/plat/i2c.h, libplatsupport/plat_include/imx93/platsupport/plat/serial.h, libplatsupport/src/plat/imx93/chardev.c, libplatsupport/src/plat/imx93/lptmr.c, libplatsupport/src/plat/imx93/serial.c, libplatsupport/src/plat/tqma8xqp1gb/serial.c
Works with the ARM generic timer when `KernelArmExportPCNTUser` and `KernelArmExportPTMRUser` are enabled. The Low Power Timer driver is in progress and will be added soon.
=> Initial i.MX93 support

libplatsupport/src/mach/cva6/serial.c
This was previously giving a build warning regarding it only being defined within this file itself.
```c
/util_libs/libplatsupport/src/mach/cva6/serial.c:12:28: warning: ‘struct dev_defn’ declared inside parameter list will not be visible outside of this definition or declaration
12 | int uart_init(const struct dev_defn *defn,
|                            ^~~~~~~~
```
=> cva6: add missing chardev include for dev_defn

libplatsupport/CMakeLists.txt, libplatsupport/include/platsupport/ltimer.h
Previously this would be a linker error later.
Now this should hopefully make it clear by removing the prototypes and so should create a compile error (if flags are set correctly).
https://github.com/seL4/sel4bench/pull/55
Style failures are unrelated.
=> libplatsupport: export a config if no ltimer

libplatsupport/CMakeLists.txt, libplatsupport/include/platsupport/ltimer.h
As suggested by Indan to be clearer to understand. https://github.com/seL4/util_libs/pull/196#issuecomment-2918974119
Needs to be merged **with** the corresponding PRs to seL4_libs (https://github.com/seL4/seL4_libs/pull/104) and sel4bench (https://github.com/seL4/sel4bench/pull/
Test with: https://github.com/seL4/seL4_libs/pull/104
Test with: https://github.com/seL4/sel4bench/pull/58
=> export LibPlatSupportHaveTimer instead of inverse

libplatsupport/CMakeLists.txt, libplatsupport/include/platsupport/ltimer.h
Depends on https://github.com/seL4/util_libs/pull/197 to be merged first.
---
When a platform does not have `CONFIG_LIB_PLAT_SUPPORT_HAVE_TIMER` set,
we _were_ removing the declaration of `ltimer_default_init` since #193.
This was because there was also no definition and so caused a linker
error anyway, so I thought it wouldn't matter if it was defined or not.
This was fine for sel4bench uses, as we used `#ifdef` to remove the
callers of `ltimer_default_init` when there was no timer. However,
this broke sel4test: https://github.com/seL4/ci-actions/pull/411 for
Cheshire, as whilst sel4test had its CONFIG_HAVE_TIMER disabled, the
compiler still saw a call to `ltimer_default_init`:
/sel4test/apps/sel4test-driver/src/main.c: In function ‘init_timer’: …
=> fix error implicit declaration of ltimer functions

libplatsupport/CMakeLists.txt, libplatsupport/include/platsupport/ltimer.h
These were taken from the sel4test Sel4testHaveTimer config option.
~~**Do not merge** until https://github.com/seL4/util_libs/pull/195 has been merged (as it will break sel4test for more platforms)~~ ok now
=> ltimer: indicate no support for more platforms
